### ISSUE TITLE
[Android] java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by PPeanutButter** [PPeanutButter/exercise#2]
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	... 1 more
Caused by: java.io.IOException: read failed: EBADF (Bad file descriptor)
	at libcore.io.IoBridge.read(IoBridge.java:523)
	at java.io.FileInputStream.read(FileInputStream.java:313)
	at java.io.FileInputStream.read(FileInputStream.java:282)
	at com.peanut.exercise.objects.FileCompat.copyFileUseStream(Unknown Source:5)
	at com.peanut.exercise.objects.FileCompat.copyFile(Unknown Source:42)
	at com.peanut.exercise.manager.ComponentsManager.addDatabase(Unknown Source:127)
	at com.peanut.exercise.manager.ComponentsManager.addDatabase$default(Unknown Source:11)
	at com.peanut.exercise.activities.settings.DownloadActivity$onCreate$$inlined$let$lambda$1$1.invoke(Unknown Source:54)
	at com.peanut.exercise.activities.settings.DownloadActivity$onCreate$$inlined$let$lambda$1$1.invoke(Unknown Source:16)
	at com.peanut.exercise.manager.ComponentsManager$justDownload$3$onDownloadSuccessful$1.run(Unknown Source:19)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	... 3 more
Caused by: android.system.ErrnoException: read failed: EBADF (Bad file descriptor)
	at libcore.io.Linux.readBytes(Native Method)
	at libcore.io.Linux.read(Linux.java:190)
	at libcore.io.ForwardingOs.read(ForwardingOs.java:177)
	at libcore.io.BlockGuardOs.read(BlockGuardOs.java:303)
	at libcore.io.ForwardingOs.read(ForwardingOs.java:177)
	at libcore.io.IoBridge.read(IoBridge.java:513)
	... 16 more
java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.io.IOException: read failed: EBADF (Bad file descriptor)
	at libcore.io.IoBridge.read(IoBridge.java:523)
	at java.io.FileInputStream.read(FileInputStream.java:313)
	at java.io.FileInputStream.read(FileInputStream.java:282)
	at com.peanut.exercise.objects.FileCompat.copyFileUseStream(Unknown Source:5)
	at com.peanut.exercise.objects.FileCompat.copyFile(Unknown Source:42)
	at com.peanut.exercise.manager.ComponentsManager.addDatabase(Unknown Source:127)
	at com.peanut.exercise.manager.ComponentsManager.addDatabase$default(Unknown Source:11)
	at com.peanut.exercise.activities.settings.DownloadActivity$onCreate$$inlined$let$lambda$1$1.invoke(Unknown Source:54)
	at com.peanut.exercise.activities.settings.DownloadActivity$onCreate$$inlined$let$lambda$1$1.invoke(Unknown Source:16)
	at com.peanut.exercise.manager.ComponentsManager$justDownload$3$onDownloadSuccessful$1.run(Unknown Source:19)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	... 3 more
Caused by: android.system.ErrnoException: read failed: EBADF (Bad file descriptor)
	at libcore.io.Linux.readBytes(Native Method)
	at libcore.io.Linux.read(Linux.java:190)
	at libcore.io.ForwardingOs.read(ForwardingOs.java:177)
	at libcore.io.BlockGuardOs.read(BlockGuardOs.java:303)
	at libcore.io.ForwardingOs.read(ForwardingOs.java:177)
	at libcore.io.IoBridge.read(IoBridge.java:513)
	... 16 more
java.io.IOException: read failed: EBADF (Bad file descriptor)
	at libcore.io.IoBridge.read(IoBridge.java:523)
	at java.io.FileInputStream.read(FileInputStream.java:313)
	at java.io.FileInputStream.read(FileInputStream.java:282)
	at com.peanut.exercise.objects.FileCompat.copyFileUseStream(Unknown Source:5)
	at com.peanut.exercise.objects.FileCompat.copyFile(Unknown Source:42)
	at com.peanut.exercise.manager.ComponentsManager.addDatabase(Unknown Source:127)
	at com.peanut.exercise.manager.ComponentsManager.addDatabase$default(Unknown Source:11)
	at com.peanut.exercise.activities.settings.DownloadActivity$onCreate$$inlined$let$lambda$1$1.invoke(Unknown Source:54)
	at com.peanut.exercise.activities.settings.DownloadActivity$onCreate$$inlined$let$lambda$1$1.invoke(Unknown Source:16)
	at com.peanut.exercise.manager.ComponentsManager$justDownload$3$onDownloadSuccessful$1.run(Unknown Source:19)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: android.system.ErrnoException: read failed: EBADF (Bad file descriptor)
	at libcore.io.Linux.readBytes(Native Method)
	at libcore.io.Linux.read(Linux.java:190)
	at libcore.io.ForwardingOs.read(ForwardingOs.java:177)
	at libcore.io.BlockGuardOs.read(BlockGuardOs.java:303)
	at libcore.io.ForwardingOs.read(ForwardingOs.java:177)
	at libcore.io.IoBridge.read(IoBridge.java:513)
	... 16 more
android.system.ErrnoException: read failed: EBADF (Bad file descriptor)
	at libcore.io.Linux.readBytes(Native Method)
	at libcore.io.Linux.read(Linux.java:190)
	at libcore.io.ForwardingOs.read(ForwardingOs.java:177)
	at libcore.io.BlockGuardOs.read(BlockGuardOs.java:303)
	at libcore.io.ForwardingOs.read(ForwardingOs.java:177)
	at libcore.io.IoBridge.read(IoBridge.java:513)
	at java.io.FileInputStream.read(FileInputStream.java:313)
	at java.io.FileInputStream.read(FileInputStream.java:282)
	at com.peanut.exercise.objects.FileCompat.copyFileUseStream(Unknown Source:5)
	at com.peanut.exercise.objects.FileCompat.copyFile(Unknown Source:42)
	at com.peanut.exercise.manager.ComponentsManager.addDatabase(Unknown Source:127)
	at com.peanut.exercise.manager.ComponentsManager.addDatabase$default(Unknown Source:11)
	at com.peanut.exercise.activities.settings.DownloadActivity$onCreate$$inlined$let$lambda$1$1.invoke(Unknown Source:54)
	at com.peanut.exercise.activities.settings.DownloadActivity$onCreate$$inlined$let$lambda$1$1.invoke(Unknown Source:16)
	at com.peanut.exercise.manager.ComponentsManager$justDownload$3$onDownloadSuccessful$1.run(Unknown Source:19)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by PPeanutButter** [comment]
at com.peanut.exercise.manager.ComponentsManager$justDownload$3$onDownloadSuccessful
at com.peanut.exercise.manager.ComponentsManager.addDatabase
下载完后添加为数据库报错
下载出错

**Comment by PPeanutButter** [comment]
since：0.7.7
改进下载器导致的bug
需要校验sha

**Comment by PPeanutButter** [comment]
校验了还是不对，文件的描述文件块错误
