### ISSUE TITLE
[Android]java.lang.SecurityException: Permission Denial opening provider android.support.v4.content.FileProvider

### ISSUE THREAD

**Issue by PPeanutButter** [PPeanutButter/exercise#3]
java.lang.SecurityException: Permission Denial: opening provider android.support.v4.content.FileProvider from ProcessRecord{9ccfc9 24025:com.peanut.exercise/u0a967} (pid=24025, uid=10967) that is not exported from UID 10728
	at android.os.Parcel.createException(Parcel.java:1953)
	at android.os.Parcel.readException(Parcel.java:1921)
	at android.os.Parcel.readException(Parcel.java:1871)
	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:4087)
	at android.app.ActivityThread.acquireProvider(ActivityThread.java:6135)
	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2616)
	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1844)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1457)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1310)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1163)
	at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1117)
	at com.peanut.exercise.objects.FileCompat.copyFile(Unknown Source:21)
	at com.peanut.exercise.manager.ComponentsManager.addDatabase(Unknown Source:127)
	at com.peanut.exercise.manager.ComponentsManager.addDatabase$default(Unknown Source:11)
	at com.peanut.exercise.activities.ImportDBActivity$onCreate$$inlined$let$lambda$1$1.invoke(Unknown Source:22)
	at com.peanut.exercise.activities.ImportDBActivity$onCreate$$inlined$let$lambda$1$1.invoke(Unknown Source:4)
	at com.peanut.sdk.miuidialog.MIUIDialog$populatePositiveButton$$inlined$let$lambda$2.onClick(Unknown Source:61)
	at android.view.View.performClick(View.java:6608)
	at android.view.View.performClickInternal(View.java:6585)
	at android.view.View.access$3100(View.java:785)
	at android.view.View$PerformClick.run(View.java:25921)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:207)
	at android.app.ActivityThread.main(ActivityThread.java:6878)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:12698)
	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:13144)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:358)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3374)
	at android.os.Binder.execTransact(Binder.java:726)

android.os.RemoteException: Remote stack trace:
	at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:12698)
	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:13144)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:358)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3374)
	at android.os.Binder.execTransact(Binder.java:726)

**Comment by PPeanutButter** [comment]
从外部（QQ）中点击db跳转到App时提供的Uri权限问题
有时可以有时不行

**Comment by PPeanutButter** [comment]
暂时catch，未解决

**Comment by PPeanutButter** [comment]
0.7.8.4测试中
